# Generated by Django 3.1.1 on 2020-09-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200912_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
